"""Auto-generated folder-index nodes are DEMOTED in ranking, never dropped.

Why this exists (measured, dream-20260726-0300): INDEX.md/index.md artifacts
concatenate children's frontmatter summaries, so they match a query's terms
well while containing no answer. Over the 40 most-recent REAL recall questions,
10/40 (25%) returned >=1 such node in top-3, burning 11 slots a doc capable of
answering could have held.

Two properties are load-bearing and each has a test that goes RED without it:
  1. DEMOTE, not DROP -- 64 of 657 artifacts carry real digest prose (up to
     18 KB), so removal is not provably loss-free. A query whose only matches
     are index nodes must still return them.
  2. The detector is ANCHORED on filename AND head-banner. A banner-anywhere
     grep also catches docs that merely QUOTE the banner in prose; exactly two
     such docs exist corpus-wide and both are real knowledge.
"""
from pathlib import Path

import pytest

from mvm.search import W_INDEX_DEMOTE, is_autogen_index

MVM_BANNER = "Auto-generated by `mvm index`. Do not hand-edit."
MEMFS_BANNER = "_Auto-rendered by memfs from /home/mike/mvm/knowledge/areas/x/_"


def _write(root: Path, rel: str, text: str) -> None:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)


# --- detector: true positives -------------------------------------------------

def test_detects_mvm_generated_INDEX(tmp_path):
    _write(tmp_path, "a/INDEX.md", f"# a — Index\n\n{MVM_BANNER}\n\n- **[doc](doc.md)**\n")
    assert is_autogen_index(tmp_path, "a/INDEX.md") is True


def test_detects_memfs_rendered_index(tmp_path):
    _write(tmp_path, "a/index.md", f"# A\n\n{MEMFS_BANNER}\n\n## Files\n")
    assert is_autogen_index(tmp_path, "a/index.md") is True


def test_detects_at_repo_root_no_slash_in_path(tmp_path):
    _write(tmp_path, "INDEX.md", f"# Index\n\n{MVM_BANNER}\n")
    assert is_autogen_index(tmp_path, "INDEX.md") is True


# --- detector: the false-positive class the anchor exists to kill -------------

def test_doc_quoting_the_banner_in_prose_is_NOT_an_index(tmp_path):
    """Verbatim repro of resources/infrastructure/sync-gap-doctrine.md, which
    tabulates the marker as a sync rule. A banner-anywhere grep demotes it."""
    _write(tmp_path, "resources/infrastructure/sync-gap-doctrine.md", (
        "# Sync-gap doctrine\n\n"
        "| What | Propagated? | Why |\n|---|---|---|\n"
        f"| `INDEX.md` | NOT propagated | {MVM_BANNER} Re-creating each side is cheaper. |\n"
        "| Files with `_Auto-rendered by memfs` marker in head | NOT propagated | regenerated |\n"
    ))
    assert is_autogen_index(tmp_path, "resources/infrastructure/sync-gap-doctrine.md") is False


def test_real_doc_named_index_without_banner_is_NOT_demoted(tmp_path):
    """A hand-authored index.md is real knowledge -- name alone is not enough."""
    _write(tmp_path, "resources/home/index.md", "# Home\n\nPool lights are on circuit 3.\n")
    assert is_autogen_index(tmp_path, "resources/home/index.md") is False


def test_banner_below_the_head_window_is_NOT_an_index(tmp_path):
    body = "# Notes\n\n" + "\n".join(f"line {i}" for i in range(20)) + f"\n\n{MVM_BANNER}\n"
    _write(tmp_path, "a/index.md", body)
    assert is_autogen_index(tmp_path, "a/index.md") is False


def test_missing_file_is_not_an_index_and_does_not_raise(tmp_path):
    assert is_autogen_index(tmp_path, "nope/INDEX.md") is False


def test_non_index_filename_never_reads_the_file(tmp_path):
    _write(tmp_path, "a/real-doc.md", f"{MVM_BANNER}\n")
    assert is_autogen_index(tmp_path, "a/real-doc.md") is False


# --- ranking: the demotion actually reorders ---------------------------------

def _score(text_score: float, demoted: bool) -> float:
    """Mirror of search.main's scoring for the no-graph/no-hier case."""
    from mvm.search import W_TEXT
    total = W_TEXT * text_score
    return total * W_INDEX_DEMOTE if demoted else total


def test_index_node_loses_to_a_comparable_real_doc():
    """rank-1 index node (text=1.0) must fall below a real doc at text=0.90."""
    assert _score(1.0, demoted=True) < _score(0.90, demoted=False)


def test_index_node_still_beats_a_genuinely_poor_match():
    """Demotion is not annihilation: a far-worse real doc must not leapfrog."""
    assert _score(1.0, demoted=True) > _score(0.40, demoted=False)


def test_demotion_factor_is_a_demotion():
    assert 0.0 < W_INDEX_DEMOTE < 1.0


def test_demotion_preserves_retrievability_not_membership():
    """DROP-vs-DEMOTE guard: a demoted node keeps a positive, finite score, so
    a query whose only matches are index nodes still returns them ranked."""
    s = _score(1.0, demoted=True)
    assert s > 0.0


@pytest.mark.parametrize("real_text", [0.95, 0.99, 1.0])
def test_index_node_never_outranks_a_strong_real_match(real_text):
    assert _score(1.0, demoted=True) < _score(real_text, demoted=False)


# --- END-TO-END: search.main itself must APPLY the demotion -------------------
#
# The tests above prove the ARITHMETIC. They do not prove main() calls it --
# blinding `total *= W_INDEX_DEMOTE` in search.main left all of them green
# (mutation M1, 2026-07-26). That is the same asymmetry as gate #29: a suite
# that tests the mechanism and never its invocation. These cases drive the real
# main() and go RED on that mutation.

def _run_main(monkeypatch, capsys, tmp_path, candidates):
    """Drive the real search.main over a fixed candidate list."""
    from mvm import search as S
    monkeypatch.setattr(S, "text_rank", lambda *a, **k: (candidates, "sem"))
    monkeypatch.setattr(S, "fetch_metadata", lambda *a, **k: {})
    rc = S.main(["q", "--json", "--root", str(tmp_path), "--state", str(tmp_path)])
    assert rc == 0
    import json as _json
    return _json.loads(capsys.readouterr().out)


def test_main_demotes_index_node_below_real_doc(monkeypatch, capsys, tmp_path):
    """The exact measured failure: an index node at text=1.0 taking rank-1 from
    a real doc at text=0.90 that can actually answer."""
    _write(tmp_path, "kalshi/INDEX.md", f"# kalshi - Index\n\n{MVM_BANNER}\n\n- **[api](api.md)**\n")
    _write(tmp_path, "kalshi/api-field-notes.md", "# API field notes\n\nyes_bid is present.\n")
    out = _run_main(monkeypatch, capsys, tmp_path, [
        ("kalshi/INDEX.md", 1.0),
        ("kalshi/api-field-notes.md", 0.90),
    ])
    paths = [r["path"] for r in out["results"]]
    assert paths[0] == "kalshi/api-field-notes.md", f"index node still outranks real doc: {paths}"
    assert paths[1] == "kalshi/INDEX.md"


def test_main_reports_the_demotion_in_components(monkeypatch, capsys, tmp_path):
    """The flag a human reads must reflect what the scorer did."""
    _write(tmp_path, "kalshi/INDEX.md", f"# i\n\n{MVM_BANNER}\n")
    _write(tmp_path, "kalshi/api-field-notes.md", "# API field notes\n\nbody\n")
    out = _run_main(monkeypatch, capsys, tmp_path, [
        ("kalshi/INDEX.md", 1.0),
        ("kalshi/api-field-notes.md", 0.90),
    ])
    by = {r["path"]: r["components"]["index_demoted"] for r in out["results"]}
    assert by["kalshi/INDEX.md"] is True
    assert by["kalshi/api-field-notes.md"] is False


def test_main_does_not_demote_a_doc_that_merely_quotes_the_banner(monkeypatch, capsys, tmp_path):
    """End-to-end guard on the FP class: sync-gap-doctrine.md keeps rank-1."""
    _write(tmp_path, "resources/infrastructure/sync-gap-doctrine.md",
           f"# Sync-gap doctrine\n\n| `INDEX.md` | NOT propagated | {MVM_BANNER} |\n")
    _write(tmp_path, "other.md", "# Other\n\nbody\n")
    out = _run_main(monkeypatch, capsys, tmp_path, [
        ("resources/infrastructure/sync-gap-doctrine.md", 1.0),
        ("other.md", 0.90),
    ])
    assert out["results"][0]["path"] == "resources/infrastructure/sync-gap-doctrine.md"
    assert out["results"][0]["components"]["index_demoted"] is False


def test_main_still_returns_index_node_when_it_is_the_only_match(monkeypatch, capsys, tmp_path):
    """DEMOTE-not-DROP, proven through main(): sole-match index node survives."""
    _write(tmp_path, "areas/consolidate-log/index.md", f"# Consolidate Log\n\n{MEMFS_BANNER}\n")
    out = _run_main(monkeypatch, capsys, tmp_path, [("areas/consolidate-log/index.md", 1.0)])
    assert [r["path"] for r in out["results"]] == ["areas/consolidate-log/index.md"]
    assert out["results"][0]["score"] > 0.0
