"""
mvm-search: tri-mode retrieval over the indexed KB.

Three signals, combinable:
  - text:       SQLite FTS5 (BM25-ranked)            [v0; vector replaces in v0.1]
  - graph:      adjacency from markdown links + frontmatter refs
  - hierarchy:  path-distance from a subtree root or seed doc

Usage:
  mvm-search "<query>"                                  # text-only ranking
  mvm-search "<query>" --in poe2/0.5                    # restrict to subtree
  mvm-search "<query>" --near moonlaif.md               # graph proximity
  mvm-search "<query>" --kind canonical                 # frontmatter filter
  mvm-search "<query>" --in poe2/0.5 --near moonlaif.md --top-k 10
  mvm-search "<query>" --json                           # machine-readable
"""
from __future__ import annotations

import argparse
import json
import os
import sqlite3
import struct
import sys
from collections import deque
from pathlib import Path

_EMBED_MODEL = None


def _embed_model():
    global _EMBED_MODEL
    if _EMBED_MODEL is None:
        from fastembed import TextEmbedding
        _EMBED_MODEL = TextEmbedding()
    return _EMBED_MODEL


def _embed_query(text: str) -> bytes:
    emb = next(iter(_embed_model().embed([text])))
    return struct.pack(f"{len(emb)}f", *emb)

DEFAULT_ROOT = Path(os.environ.get("MVM_KNOWLEDGE", str(Path.home() / "mvm" / "knowledge")))
DEFAULT_STATE = Path(os.environ.get("MVM_STATE", str(Path.home() / "mvm" / "state")))

W_TEXT = float(os.environ.get("MVM_W_TEXT", "0.6"))
W_GRAPH = float(os.environ.get("MVM_W_GRAPH", "0.25"))
W_HIER = float(os.environ.get("MVM_W_HIER", "0.15"))

# Auto-generated folder-index artifacts (INDEX.md / index.md) are POINTER nodes:
# they concatenate children's frontmatter summaries, so they match a query's terms
# well while containing no answer. Measured 2026-07-26 (dream-20260726-0300) over
# the 40 most-recent REAL recall questions: 10/40 queries (25%) had >=1 such node
# in top-3, burning 11 top-3 slots that a doc capable of answering could have held.
#
# DEMOTE, never DROP. 64 of the 657 index nodes carry up to 18 KB of real digest
# prose, so dropping them is not provably loss-free; multiplying the score keeps
# every node retrievable (a query whose ONLY matches are index nodes still returns
# them) while ensuring one never outranks a real doc that is a comparable match.
# At 0.55 an index node must beat a real doc's normalized text score by ~2x to
# keep a slot -- it only wins when the alternatives are genuinely poor matches.
W_INDEX_DEMOTE = float(os.environ.get("MVM_W_INDEX_DEMOTE", "0.55"))


_AUTOGEN_BANNERS = ("Auto-generated by `mvm index`", "Auto-rendered by memfs")


def is_autogen_index(root: Path, rel: str) -> bool:
    """True iff `rel` is an auto-generated folder-index artifact.

    ANCHORED ON BOTH filename AND a banner in the head, deliberately. A
    banner-anywhere grep is wrong: it also catches docs that merely QUOTE the
    banner in prose -- measured corpus-wide 2026-07-26, exactly two such docs
    exist (`resources/infrastructure/sync-gap-doctrine.md`, which tabulates the
    marker as a sync rule, and `areas/research-queue-cold.md`). Both are real
    knowledge and must never be demoted. The anchor kills both and loses none
    of the 657 genuine artifacts (anchored-but-not-naive == 0).
    """
    if rel.rsplit("/", 1)[-1] not in ("INDEX.md", "index.md"):
        return False
    try:
        with open(Path(root) / rel, errors="ignore") as fh:
            head = "".join(next(fh, "") for _ in range(5))
    except OSError:
        return False
    return any(b in head for b in _AUTOGEN_BANNERS)


def hierarchy_distance(path_a: str, path_b: str) -> int:
    """Number of directory hops from path_a to path_b (lower = closer)."""
    pa = Path(path_a).parts
    pb = Path(path_b).parts
    common = 0
    for x, y in zip(pa, pb):
        if x == y:
            common += 1
        else:
            break
    return (len(pa) - common) + (len(pb) - common)


def graph_distances(graph_db: Path, seed: str, max_depth: int = 4) -> dict[str, int]:
    """BFS from seed in the bidirectional link graph. Returns {path: distance}."""
    if not graph_db.exists():
        return {}
    conn = sqlite3.connect(graph_db)
    cur = conn.cursor()
    distances = {seed: 0}
    queue = deque([(seed, 0)])
    while queue:
        node, d = queue.popleft()
        if d >= max_depth:
            continue
        cur.execute("SELECT dst FROM edges WHERE src = ?", (node,))
        for (dst,) in cur.fetchall():
            if dst not in distances:
                distances[dst] = d + 1
                queue.append((dst, d + 1))
        cur.execute("SELECT src FROM edges WHERE dst = ?", (node,))
        for (src,) in cur.fetchall():
            if src not in distances:
                distances[src] = d + 1
                queue.append((src, d + 1))
    conn.close()
    return distances


def vec_search(index_db: Path, query: str, kind: str | None, in_prefix: str | None,
               limit: int = 50, cos_out: dict[str, float] | None = None) -> list[tuple[str, float]]:
    """Vector cosine search via sqlite-vec. Returns [(path, normalized_score)] desc.

    `cos_out`, when given, is filled with {path: ABSOLUTE cosine} — the one
    signal in this file that survives no normalization. It is an OUT-param and
    never affects ordering; the return value is byte-identical with or without
    it. It exists because every score this module publishes is max-normalized,
    so `mvm search --json` could report NO absolute match quality anywhere, and
    a consumer that needs "is this pair actually similar?" (see /dream's
    tension gate) was forced to threshold a ratio of rank-reciprocals instead.

    ⚠ `limit` is CLAMPED to VEC_K_MAX (4096). sqlite-vec rejects a knn `k` above
    that with `OperationalError: k value in knn query too large`, and the
    OperationalError handler below turns ANY query failure into `rows = []` —
    which `text_rank` cannot distinguish from "the vector leg legitimately
    matched nothing", so it silently degrades to an FTS-only retriever.
    Measured 2026-07-26: k=4823 returned 0 docs while k=4000 returned 4000, with
    nothing on any channel saying why. That is gate #47 again — the return value
    asserts a fact about the CORPUS while reporting an event in the QUERY.
    Unreachable before MVM_VEC_POOL existed (`limit` was hardcoded 50 at both
    call sites); adding the knob made it reachable, so it is clamped and loud
    here rather than left as a trap for whoever tunes the pool next.
    """
    if not index_db.exists():
        return []
    if limit > VEC_K_MAX:
        print(f"mvm: vec pool {limit} exceeds sqlite-vec's k limit "
              f"{VEC_K_MAX}; clamping (the vector leg stays alive)",
              file=sys.stderr)
        limit = VEC_K_MAX
    conn = sqlite3.connect(index_db)
    conn.enable_load_extension(True)
    try:
        import sqlite_vec
        sqlite_vec.load(conn)
        conn.enable_load_extension(False)
    except Exception:
        conn.close()
        return []

    try:
        q_blob = _embed_query(query)
    except Exception:
        conn.close()
        return []

    cur = conn.cursor()
    # vec0 returns rows ordered by distance (ascending) when MATCH'd.
    sql = """
        SELECT v.path, v.distance
        FROM files_vec v
        JOIN files f ON f.path = v.path
        WHERE v.embedding MATCH ? AND k = ?
    """
    params: list = [q_blob, limit]
    if kind:
        sql += " AND f.kind = ?"
        params.append(kind)
    if in_prefix:
        sql += " AND f.path LIKE ?"
        params.append(f"{in_prefix.rstrip('/')}%")

    try:
        cur.execute(sql, params)
        rows = cur.fetchall()
    except sqlite3.OperationalError as e:
        # NEVER silently: an empty `rows` here becomes "the vector leg found
        # nothing" one frame up, and text_rank then serves an FTS-only ranking
        # under the label "hybrid". Degrading is acceptable; degrading quietly
        # is how a retriever loses a whole leg for weeks without a single line
        # of evidence anywhere.
        print(f"mvm: vector leg FAILED ({e}) — ranking with the keyword leg "
              f"ONLY; this is a degraded retrieval, not an empty corpus",
              file=sys.stderr)
        rows = []
    conn.close()
    if not rows:
        return []
    # vec0 `distance` is PLAIN L2 (not squared) over UNIT vectors — verified
    # 2026-07-26 against a numpy oracle on live rows: stored norms are exactly
    # 1.000000, and 1 - d*d/2 reproduced numpy's cosine to 6 decimals while the
    # legacy 1 - d/2 did not (d=0.4646 → true cos 0.8921, legacy 0.7677).
    #
    # ⚠ THE LEGACY TRANSFORM BELOW IS DELIBERATELY LEFT UNCHANGED. It is
    # monotone decreasing in d, so ordering — and therefore every ranking this
    # module has ever produced — is identical either way; it is a DISPLAY scale
    # that has been mis-labelled "cosine", not a ranking bug. Correcting it in
    # place would silently move published `components.text` values on the
    # non-hybrid path for zero ranking gain, so the honest fix is to stop the
    # NAME from over-claiming and to carry the real quantity on its own channel.
    sims = [(p, max(0.0, 1.0 - d / 2.0)) for p, d in rows]
    if cos_out is not None:
        # True cosine, absolute and un-normalized: cos = 1 - L2^2/2 for unit vectors.
        for p, d in rows:
            cos_out[p] = max(-1.0, min(1.0, 1.0 - (d * d) / 2.0))
    max_s = max(s for _, s in sims) or 1.0
    return [(p, s / max_s) for p, s in sims]


def fts_tokens(query: str) -> list[str]:
    """Split a natural-language query into FTS5-safe bare tokens.

    FTS5's MATCH grammar treats `,` `.` `(` `)` `:` `-` `*` `"` as OPERATORS, so
    ANY sentence-shaped query raises `fts5: syntax error near ","` -- which the
    old handler swallowed into an empty result, indistinguishable from "the
    keyword signal legitimately found nothing". Measured 2026-07-26 over the
    1,959 real questions in `state/recall-log.jsonl`: **90.1% raised a syntax
    error**, so `text_rank` fell through to the vector-only `sem` branch and the
    advertised hybrid retriever was keyword-blind for nine of every ten real
    queries, silently, since the 2026-07-01 cutover.

    Keeping only alphanumerics is deliberate over escaping: it cannot construct
    a token FTS5 reads as punctuation-syntax, so that failure mode is closed by
    construction rather than by a blacklist the next punctuation mark escapes.

    Stripping alone is NOT sufficient, and this test caught it: a surviving bare
    word can still BE an operator -- `AND` `OR` `NOT` `NEAR` are FTS5 keywords
    (uppercase only), so the legitimate question "Kalshi AND WTI ladder" still
    raised a syntax error after sanitization. Callers therefore quote every
    token as an FTS5 string literal; with all non-alphanumerics already gone
    there is no embedded quote to escape, so quoting is total.
    """
    toks = []
    for raw in query.split():
        t = "".join(ch for ch in raw if ch.isalnum())
        if t:
            toks.append(t)
    return toks


def fts_expr(toks: list[str], op: str) -> str:
    """Join sanitized tokens into an FTS5 expression, each quoted as a literal."""
    return f" {op} ".join(f'"{t}"' for t in toks)


def fts_search(index_db: Path, query: str, kind: str | None, in_prefix: str | None,
               limit: int = 50) -> list[tuple[str, float]]:
    """FTS5 BM25 fallback. Returns [(path, normalized_score)] descending."""
    if not index_db.exists():
        return []
    toks = fts_tokens(query)
    if not toks:
        return []
    conn = sqlite3.connect(index_db)
    cur = conn.cursor()
    sql = (
        "SELECT files_fts.path, bm25(files_fts) AS score "
        "FROM files_fts JOIN files ON files.path = files_fts.path "
        "WHERE files_fts MATCH ?"
    )
    tail = ""
    extra: list = []
    if kind:
        tail += " AND files.kind = ?"
        extra.append(kind)
    if in_prefix:
        tail += " AND files.path LIKE ?"
        extra.append(f"{in_prefix.rstrip('/')}%")
    tail += " ORDER BY score LIMIT ?"

    # AND-of-all-terms first (precise), OR as a fallback ONLY when AND is empty.
    # Strictly additive: every query the conjunction already answered keeps its
    # exact prior ranking, and the disjunction runs solely where the keyword
    # signal was otherwise contributing nothing. Measured on the same 1,959
    # questions: of the 193 that were syntactically legal, 48 (24.9%) still
    # returned zero rows because one rare term vetoed the whole conjunction.
    rows = []
    for expr in (fts_expr(toks, "AND"), fts_expr(toks, "OR")):
        try:
            cur.execute(sql + tail, [expr] + extra + [limit])
            rows = cur.fetchall()
        except sqlite3.OperationalError as e:
            # Sanitization above makes this unreachable for syntax; if it fires
            # anyway the keyword half is DEAD and must say so out loud rather
            # than pose as an empty result set.
            if "syntax" in str(e).lower():
                print(f"mvm-search: FTS5 rejected sanitized query {expr!r}: {e}",
                      file=sys.stderr)
                rows = []
            elif "no such" in str(e).lower():
                rows = []
            else:
                conn.close()
                raise
        if rows:
            break
        if len(toks) == 1:
            break
    conn.close()
    if not rows:
        return []
    raw = [(p, -s) for p, s in rows]
    max_s = max(s for _, s in raw) or 1.0
    return [(p, s / max_s) for p, s in raw]


RRF_K = int(os.environ.get("MVM_RRF_K", "60"))
# FTS votes at half a vector vote: vector is the primary whole-doc semantic
# signal; BM25 is a keyword corroborator with a known keyword-bag pathology.
# Satisfiable interval from the frozen probes: (~0.2, ~0.75); 0.5 = midpoint.
RRF_W_FTS = float(os.environ.get("MVM_RRF_W_FTS", "0.5"))

# Vector-leg candidate pool. Distinct lever from k/w_fts (both dead, see
# rrf_fuse): k and w_fts move the head-to-head between two docs BOTH legs
# already returned; VEC_POOL changes WHICH docs the vector leg returns at all.
# The arithmetic that motivates it: an FTS-rank-1 doc contributes
# 0.5/(60+1)=0.00820 == a vec-rank-61 contribution, into a 50-doc vector pool —
# so a doc that is the single best exact-keyword match but absent from vec
# top-50 cannot outrank ANY vector result. Widening is a strict SUPERSET of the
# current candidate set (it can only add votes, never remove a candidate),
# unlike the rejected reachability floor which FORCED a chosen doc into a slot.
# ⚠ It is not free in the other direction: a vec-rank-51 doc with no keyword
# vote scores 1/112=0.00893 > an FTS-rank-1-only doc's 0.00820, so widening can
# also displace exact-keyword matches with weak semantic neighbours. Which
# effect dominates is an empirical question — graded on `mvm-retrieval-sweep`.
#
# ⛔ DEAD LEVER — MEASURED AND REJECTED 2026-07-26. Do not re-derive.
# Pre-registered bar: ship the smallest pool gaining >=+2.0pp recall@5 at a cost
# of <=0.5pp top-1, on the 155-question held-out sweep. Measured, n=155 both:
#     pool  50 (base): recall@5 78.7% (122/155) · top-1 51.0% (79/155) · 23.3s
#     pool 100       : recall@5 79.4% (123/155) · top-1 50.3% (78/155) · 31.3s
#     pool 200       : recall@5 79.4% (123/155) · top-1 50.3% (78/155) · 22.9s
#     pool 400       : recall@5 79.4% (123/155) · top-1 50.3% (78/155) · 29.4s
# ⇒ +0.6pp recall for -0.6pp top-1: ONE question gained, ONE lost. Fails BOTH
# halves of the bar. Per-question diff: only 4 of 155 top-5 rankings move at all
# (contrast the rejected reachability floor's 33), and 100->400 moves ZERO — the
# lever SATURATES by pool 100 and every larger pool is pure latency.
#
# WHY it saturates, which is the durable part: a vec-rank-r doc carrying no
# keyword vote scores 1/(61+r), which drops below an FTS-rank-1-only doc's
# 0.5/61 == 1/122 once r > 61. So candidates past vec-rank ~61 can never win on
# the vector vote alone; they can only ADD to a doc that already holds an FTS
# vote, and the FTS pool is 50 docs. Widening therefore has a small, bounded
# reachable set by construction — no pool value unlocks the tail.
#
# ⚠ AND IT IS NON-MONOTONIC — the trap for anyone who retries this. On the
# known reproducer ("grasping mail breach modifier chaos spam") the target's
# FUSED rank goes 51 (pool 50) -> 63 (pool 100) -> 13 (pool 200) -> 13 (400):
# widening makes it WORSE until the target actually enters the pool (it sits at
# vec-rank 120), because ranks 51-61 of the new candidates outscore it first.
# A two-point pool comparison can therefore read "helps" or "hurts" at will.
# NOTE the reproducer still fails at every pool (target lands rank 13, not top-8)
# — so the pool is not the binding constraint on it either. The vector leg puts
# the single best exact-keyword doc at rank 120 of 4,824; that is an EMBEDDING
# failure ("...mail...spam" -> email spam), and the next rung is the embedding
# model / query expansion, NOT the plumbing around it.
VEC_POOL = int(os.environ.get("MVM_VEC_POOL", "50"))
# sqlite-vec's hard ceiling on a knn `k`. Above it the query RAISES, and a
# raise here is indistinguishable from an empty corpus downstream — see
# vec_search's docstring.
VEC_K_MAX = 4096


def rrf_fuse(vec_results: list[tuple[str, float]], fts_results: list[tuple[str, float]],
             k: int = RRF_K, w_fts: float = RRF_W_FTS) -> list[tuple[str, float]]:
    """Reciprocal Rank Fusion of the two retrievers.

    Rank-based, so BM25 and cosine scores never need to share a scale — the
    fix for the cross-domain saturation defect (2026-07-01): max-normalized
    cosine sims put PoE2 noise at sem~1.000 on Kalshi queries while an
    exact-keyword doc sat FTS-rank-1 unseen (FTS only ran as a fallback).
    Output is max-normalized for display continuity only; ordering is pure RRF.

    THE EXACT-MATCH REACHABILITY LIMIT — derived, then MEASURED AND REJECTED
    -----------------------------------------------------------------------
    ⛔ Read this before "fixing" the known reproducer. Two plausible repairs
    are already dead; re-deriving them costs a session.

    Reproducer: `mvm search "grasping mail breach modifier chaos spam"` returns
    ZERO PoE2 docs in the top 8. Leg-split: FTS puts the correct doc at rank 1;
    the vector leg reads "…mail … spam" as EMAIL SPAM and never returns it at
    all (absent from its top-50 pool).

    (a) LOWERING k CANNOT FIX IT. A doc's vote is w/(k+rank+1), so in a
    head-to-head at EQUAL rank k CANCELS EXACTLY:

        fts-rank-1  w/(k+1)      ratio = w for EVERY k
        vec-rank-1  1/(k+1)                (0.5 here)

    A doc carrying only the down-weighted leg's vote can never outrank a doc at
    the same rank in the full-weight leg, at any k. In general an FTS-rank-1 doc
    outranks vec-rank r only when r > k+2, so top-5 demands k<=2; measured
    2026-07-26, only k=1 (degenerate RRF) surfaced it. ⇒ k and w_fts are NOT two
    levers on this defect: k sets how far down the OTHER leg you can reach; only
    w_fts moves the head-to-head, and w_fts is pinned by the derivation above.

    (b) AN EXACT-MATCH REACHABILITY FLOOR was then built and REJECTED ON
    EVIDENCE (2026-07-26): give the top FTS doc a guaranteed rank-5 slot when
    the vector leg never saw it. It fixed the reproducer AND took the frozen
    6-case eval 5/6 -> 6/6 (CD1 green) — and the 155-question held-out oracle
    `mvm-retrieval-sweep` read a REGRESSION: recall@5 78.7% -> 77.4%, top-1 flat
    at 51.0%. Per-question diff: the floor changed 33 of 155 rankings (NOT the
    rare maximal-disagreement case its design assumed), gaining 1 and losing 3.
    The losses name the cause: BM25 rank-1 is frequently a keyword-bag artifact,
    which is the exact pathology w_fts=0.5 exists to suppress — so the floor was
    a structural back door to the same overfit that tuning w_fts was rejected
    for, and it displaced genuinely-correct rank-5 docs to install worse ones.

    ⚠ NOTE WHAT BOTH REJECTED CHANGES SHARE: w_fts=1.0 and the floor each take
    the 6-case eval 5/6 -> 6/6 while failing held-out. CD1 is an overfit magnet —
    any change that boosts the FTS leg passes it. Grade ranker changes on
    `mvm-retrieval-sweep` (n=155), never on the 6-case eval alone.
    """
    scores: dict[str, float] = {}
    for rank, (p, _) in enumerate(vec_results):
        scores[p] = scores.get(p, 0.0) + 1.0 / (k + rank + 1)
    for rank, (p, _) in enumerate(fts_results):
        scores[p] = scores.get(p, 0.0) + w_fts / (k + rank + 1)
    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    if not ranked:
        return []
    max_s = ranked[0][1] or 1.0
    return [(p, s / max_s) for p, s in ranked]


def text_rank(index_db: Path, query: str, kind: str | None, in_prefix: str | None,
              limit: int = 50, root: Path | None = None,
              cos_out: dict[str, float] | None = None) -> tuple[list[tuple[str, float]], str]:
    """Text-signal ranking. Returns (results, retriever_label).

    `cos_out` is a pass-through OUT-param (see vec_search): absolute cosine per
    path, ordering-neutral. A path absent from it was never returned by the
    vector leg at all — that absence is itself the signal, and it must NOT be
    read as cosine 0.0 (an FTS-only hit and a genuinely orthogonal doc are
    different facts).

    Default (MVM_HYBRID=1) → RRF fusion of vector + FTS ("hybrid").
    MVM_HYBRID=0           → legacy path: vector first, FTS only as
                             empty-fallback. Kill switch for the 2026-07-01
                             cutover (frozen eval: test/eval_crossdomain.py).
    """
    root = root or DEFAULT_ROOT
    hybrid = os.environ.get("MVM_HYBRID", "1") == "1"
    if hybrid:
        # The vector leg gets its own pool size (VEC_POOL, default 50 == the
        # caller's limit ⇒ identity). Held separate from `limit` on purpose:
        # the FTS leg is a keyword corroborator whose tail is keyword-bag noise,
        # so widening BOTH legs would confound the lever being measured.
        vec = vec_search(index_db, query, kind, in_prefix, limit=max(limit, VEC_POOL),
                         cos_out=cos_out)
        fts = fts_search(index_db, query, kind, in_prefix, limit=limit)
        # Navigation files (auto-generated INDEX.md / index.md) are keyword
        # bags — BM25 ranks them above the content they merely list, whenever
        # they match at all (eval 2026-07-01: PC1/PC2 regression). Drop them
        # from the FTS vote only; they stay reachable via the vector signal,
        # which is exactly how the legacy path ranked them.
        #
        # Uses the SAME anchored predicate as the scoring-stage demote, which
        # this line used to disagree with: a filename-only test also dropped
        # HAND-AUTHORED navigation docs that carry real routing knowledge.
        # Measured 2026-07-26: 9 such docs, including `resources/index.md` (the
        # root routing table) and `areas/index.md`, were being denied a keyword
        # vote while `is_autogen_index` correctly spared them. Two definitions
        # of "index node" in one file is the drift; one predicate is the fix.
        fts = [(p, s) for p, s in fts if not is_autogen_index(root, p)]
        if vec and fts:
            return rrf_fuse(vec, fts), "hybrid"
        if vec:
            return vec, "sem"
        return fts, "fts"
    results = vec_search(index_db, query, kind, in_prefix, limit=limit, cos_out=cos_out)
    if results:
        return results, "sem"
    return fts_search(index_db, query, kind, in_prefix, limit=limit), "fts"


def fetch_metadata(index_db: Path, paths: list[str]) -> dict[str, dict]:
    if not paths or not index_db.exists():
        return {}
    conn = sqlite3.connect(index_db)
    cur = conn.cursor()
    placeholders = ",".join("?" * len(paths))
    cur.execute(
        f"SELECT path, kind, source, ingested_at, n_tests FROM files WHERE path IN ({placeholders})",
        paths,
    )
    out = {}
    for path, kind, source, ingested_at, n_tests in cur.fetchall():
        out[path] = {
            "kind": kind, "source": source,
            "ingested_at": ingested_at, "n_tests": n_tests,
        }
    conn.close()
    return out


def main(argv = None) -> int:
    parser = argparse.ArgumentParser(description="Tri-mode retrieval (text + graph + hierarchy).")
    parser.add_argument("query", help="Search query.")
    parser.add_argument("--in", dest="in_prefix", help="Restrict to subtree (path prefix).")
    parser.add_argument("--near", help="Graph proximity seed (rel-path or wikilink).")
    parser.add_argument("--kind", help="Filter by frontmatter kind (e.g. canonical, log).")
    parser.add_argument("--top-k", type=int, default=5, help="Top-K results (default: 5).")
    parser.add_argument("--state", type=Path, default=DEFAULT_STATE,
                        help=f"State dir (default: {DEFAULT_STATE}).")
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT,
                        help=f"Knowledge root (default: {DEFAULT_ROOT}).")
    parser.add_argument("--json", action="store_true", help="Emit JSON.")
    args = parser.parse_args(argv)

    index_db = args.state / "index.db"
    graph_db = args.state / "graph.db"

    # Text signal: hybrid RRF fusion when MVM_HYBRID=1, else legacy vec-then-fts.
    abs_cos: dict[str, float] = {}
    text_results, retriever = text_rank(index_db, args.query, args.kind, args.in_prefix,
                                        limit=50, root=args.root, cos_out=abs_cos)
    if not text_results:
        if args.json:
            print(json.dumps({"query": args.query, "results": []}))
        else:
            print("(no results)")
        return 0

    graph_dist: dict[str, int] = {}
    if args.near:
        graph_dist = graph_distances(graph_db, args.near)

    seed_for_hier = args.near or (args.in_prefix or "")
    scored: list[tuple[str, float, dict]] = []
    for path, text_score in text_results:
        gd = graph_dist.get(path)
        graph_score = 1.0 / (gd + 1) if gd is not None else 0.0
        if seed_for_hier:
            hd = hierarchy_distance(seed_for_hier, path)
            hier_score = 1.0 / (hd + 1)
        else:
            hier_score = 0.0
        total = (W_TEXT * text_score + W_GRAPH * graph_score + W_HIER * hier_score)
        demoted = is_autogen_index(args.root, path)
        if demoted:
            total *= W_INDEX_DEMOTE
        # `cos` is the ONLY absolute quantity published here: true cosine in
        # [-1,1], never max-normalized, never rank-derived. `null` means the
        # vector leg did not return this path (FTS-only hit) — that is "unknown",
        # NOT "dissimilar", and a consumer that collapses the two is measuring
        # pool membership while calling it similarity.
        scored.append((path, total, {
            "text": round(text_score, 4),
            "cos": (round(abs_cos[path], 4) if path in abs_cos else None),
            "graph": round(graph_score, 4),
            "hier": round(hier_score, 4),
            "graph_dist": gd,
            "index_demoted": demoted,
        }))

    scored.sort(key=lambda x: x[1], reverse=True)
    top = scored[: args.top_k]

    meta = fetch_metadata(index_db, [p for p, _, _ in top])

    if args.json:
        print(json.dumps({
            "query": args.query,
            "retriever": retriever,
            "filters": {"in": args.in_prefix, "near": args.near, "kind": args.kind},
            "weights": {"text": W_TEXT, "graph": W_GRAPH, "hier": W_HIER},
            "results": [
                {"path": p, "score": round(s, 4), "components": c, "metadata": meta.get(p, {})}
                for p, s, c in top
            ],
        }, indent=2))
    else:
        print(f"query: {args.query}")
        if args.in_prefix or args.near or args.kind:
            filters = []
            if args.in_prefix: filters.append(f"in={args.in_prefix}")
            if args.near: filters.append(f"near={args.near}")
            if args.kind: filters.append(f"kind={args.kind}")
            print(f"filters: {' '.join(filters)}")
        print()
        for path, score, comp in top:
            m = meta.get(path, {})
            kind_str = f" [{m['kind']}]" if m.get("kind") else ""
            tests_str = f" tests={m['n_tests']}" if m.get("n_tests") else ""
            print(f"  {score:.3f}  {path}{kind_str}{tests_str}")
            print(f"          {retriever}={comp['text']:.3f} graph={comp['graph']:.3f} hier={comp['hier']:.3f}")
    return 0


if __name__ == "__main__":  # `python3 -m mvm.<mod>` must RUN, never silently exit 0
    sys.exit(main())
